[project]
name = "UNF-v3"
version = "0.3.1-beta"
description = "DoPy Billing Software"

[tool.cxfreeze]
executables = [
    {script = "main.py", base = "gui", icon="dopylogofinal"}
]

[tool.cxfreeze.build_exe]
optimize = 2
